CI: azure
c_compiler: gcc
cdt_name: conda
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: quay.io/condaforge/linux-anvil-x86_64:alma9
extend_keys:
- ignore_build_only_deps
- pin_run_as_build
- ignore_version
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.26'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: 3.12.* *_cpython
python_min: '3.9'
r_base: '3.5'
target_platform: linux-64
